config/routes.rb
Autoshipping::Application.routes.draw do
  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :registration => 'register', :sign_up => 'sign_up'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "profile", to: 'user#show'
  get "info/faq"
  get "info/about"

  get 'about', to: 'info#about'
  get 'faq', to: 'info#faq'
  resources :cars, only: [:index, :show, :catalog]
  get 'catalog', to: 'cars#catalog'
  get 'auction', to: 'cars#auction'
  get 'search', to: 'cars#search'
  root 'cars#index'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/car.rb
class Car < ActiveRecord::Base
  before_create :rus_translate
  scope :index, -> { where.not(:engine_volume=> 0.0) }
  scope :state, -> (d){where(:state=> d)}
  belongs_to :model
  
  has_one :manufacturer, through: :model
  has_many :images, dependent: :destroy

  attr_protected nil

  validates_presence_of :model, :release_year, :manufacturer_id

  BODY_TYPES = %w(sedan minivan coupe convertible hatchback crossover suv pickup fullsize-van truck moto)
  private
    def rus_translate
      self.damage= I18n.t self.damage

      self.transmission= I18n.t self.transmission
    end
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_reader :from_url
  belongs_to :car

  has_attached_file :file,
    styles: {small: ["70x70>", :jpg], big: ["417x299>", :jpg]}
  def from_url=(url_value)
    self.file = URI.parse(url_value)
    @from_url=url_value
  end
  def image_url
    self.file.url(:small)
  end
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base

  has_many :models
  has_many :cars, through: :models
  attr_protected nil

  validates_presence_of :title
end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :manufacturer

  has_many :cars

  validates_presence_of :name, :manufacturer_id
  validates_uniqueness_of :name, scope: :manufacturer_id

  attr_protected nil

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :name, :last_name, :email, :address, :password, :password_confirmation, :remember_me
  attr_accessible :avatar
  validates :name, :last_name, :email, :address, presence: {message: "Поле должно быть заполнено"}
  has_attached_file :avatar, :styles => { :medium => "120x120>", :thumb => "60x60>" }
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_params, if: :devise_controller?

  protect_from_forgery with: :exception
  protected
  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :last_name, :email, :address, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name, :last_name, :email, :address,  :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :show_default_new_cars, only: :auction
  before_action :ensure_search_params
  def index
     @q = Car.index.search(params[:q])
     @cars=@q.result(distinct: true).page(params[:page]).per(12)
  end   

  def show
    @car = Car.find params[:id]   
    @related=Car.where("id !=? AND model_id =?", @car.id, @car.model_id).limit(3)
  end

  def catalog
    @q = Car.search(params[:q])
    @cars=@q.result(distinct: true).where(:source_site=>'').page(params[:page]).per(12)
  end

  def auction
    @q = Car.search(params[:q])
    @cars=@q.result(distinct: true).where.not(source_site:'none').state(params[:state]).page(params[:page]).per(16)
  end

  def search
    @q = Car.index.search(params[:q])
    @cars=@q.result(distinct: true).page(params[:page]).per(18)
  end

  private
    def show_default_new_cars
      params[:state]||= 'new'
    end
    def ensure_search_params
      params[:q] ||= {}
    end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def faq
  end

  def about
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!, only: :update
  def new
    @user=User.new
  end
  def create
    @user=User.create!(params[:user])
  end
  def update
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
  
  def resource
    @resource ||= User.new
  end
  
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cars/_car.html.erb
<div class="card">
  <div class="tit"><%= link_to car.manufacturer.title+' '+car.model.name, car %></div>
  <div class="meta">
    <div class="image"><a href="<%= car_path car %>">
    <%if car.images.any?%><%= image_tag car.images.first.url, size: "70x70"%><%end%></a></div>
    <div class="price"><%= car.price %></div>
  </div>
  <div class="info">
    <ul>
      <li><span>пробег:</span> <%=car.odometer%></li>
      <li><span>цвет:</span> <%=car.color%></li>
      <li><span>КПП:</span> <%=car.transmission%></li>
      <li><span>привод:</span> <%=car.drive%></li>
      <li><span>объем:</span> <%=car.engine_volume%>Л</li>
      <li><span>VIN:</span><%=car.vin%></li>
    </ul>
  </div>
</div>

app/views/cars/_filter.html.erb
<div id="search" class="forms">
  <!-- <form action="#" method="get"> -->
  <%= form_for @q, url: (path), method: :get do |f| %>
    <div class="searchform clearfix">
      <!-- <input name="" type="text" class="col-lg-11"> -->
      <%= f.text_field :manufacturer_title_or_model_name_cont, :class=>"col-lg-11"%>
      <button type="submit" class="button col-lg-1"><span></span></button>
    </div>
    <div class="advanced">
      <a href="#" class="close">скрыть</a>
      <ul class="nav nav-tabs">
        <li><a href="#advancedOptions" data-toggle="tab">Расширенные параметры</a></li>
        <li><a href="#moreOptions" data-toggle="tab">Дополнительные параметры</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane" id="advancedOptions">
          <div class="row">
            <div class="col-lg-4">
              <div class="form-group form-mark">
                <%= f.label 'марка автомобиля'%>
                <%= f.collection_select :manufacturer_id_eq, Manufacturer.order(:title), :id, :title, prompt: 'Выберите марку',:width=>146 %>
                </div>
              <div class="form-group form-model">
                <%= f.label 'модель автомобиля'%>
                 <%= f.grouped_collection_select :model_id_eq, Manufacturer.order(:title), :models, :title, :id, :name, prompt: 'Выберите модель', :id=>"modelSelect", :width=>146 %>
              </div>
              <div class="form-group">
                <%= f.label "состояние авто"%>
                <% %w(new used).zip(%w(новые с_пробегом)).each do |state, text|%>
                <div class="group left">
                <%= f.check_box :state_eq, {},state, false %>
                <%= f.label "#{text}"%>
<!--                   <label for="newCheckbox"><input name="" type="checkbox" value="" id="newCheckbox">новые</label>
                </div>
                <div class="group left">
                  <label for="mileageCheckbox"><input name="" type="checkbox" value="" id="mileageCheckbox">с пробегом</label> -->
                </div>
                <%end%>
                <div class="clearfix"></div>
              </div>
            </div>
            <div class="col-lg-4">
            <div class="form-group form-year">
                <!-- <label for="modelSelect">год выпуска:</label> -->
                <%= f.label 'год выпуска'%>
                <div class="filterbar">
                  <!-- <input type="text" value="1987"> -->
                  <%= f.text_field :release_year_gt %>
                  <%= f.hidden_field :release_year_gt %>
                  <!-- <input type="text" value="2007"> -->
                  <%= f.text_field :release_year_lt %>
                  <%= f.hidden_field :release_year_gt %>
                </div>
              </div>
              <div class="form-group form-price">
                <!-- <label for="modelSelect">цена</label>
                <input type="text" value="1"> -->
                  <%= f.label 'цена' %>
                  <%= f.text_field :price_gt %>
                <span class="sep">&mdash;</span>
                <!-- <input type="text" value="9 999 999"> -->
                  <%= f.text_field :price_lt %>
                <select name="" id="">
                  <option value=""> у.е.</option>
                </select>
              </div>
              <div class="form-group">
                <%= f.label "Коробка передач"%>
                <% %w(автомат механика).each_with_index do |transmis, ind|%>
                  <div class="group left">
                    <%= f.check_box :transmission_eq, {},transmis, false %>
                    <%= f.label "#{transmis}"%>
                    <!-- <label for="automaticCheckbox"><input name="" type="checkbox" value="" id="automaticCheckbox">автомат</label> -->
                   
                  </div>
                <%end%>
                <div class="clearfix"></div>
              </div>
            </div>
            <div class="col-lg-4">
            <%= f.label 'кузов'%>
              <div class="cars_body">
              <% %w(sedan minivan coupe convertible hatchback crossover suv pickup fullsize truck moto).each do |body_type|%>
                <%= link_to image_tag('i_blank.jpg'),  params.merge(:q=>{:car_body_eq=>body_type}), :class=> "car-#{body_type}"%>
                <%end%>
                <%= f.hidden_field :car_body_eq%>
 <!--           <a href="" class="car-sedan"></a>
                <a href="#" class="car-minivan"></a>
                <a href="#" class="car-coupe"></a>
                <a href="#" class="car-convertible"></a>
                <a href="#" class="car-hatchback"></a>
                <a href="#" class="car-crossover"></a>
                <a href="#" class="car-suv"></a>
                <a href="#" class="car-pickup"></a>
                <a href="#" class="car-fullsize-van"></a>
                <a href="#" class="car-truck"></a>
                <a href="#" class="car-moto"></a> -->
              </div>
            </div>
          </div>
        </div>
        <div class="tab-pane" id="moreOptions"></div>
      </div>

    </div>
  <% end %>
</div><!-- /search -->

app/views/cars/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-lg-8">
      <div class="subscribe">
        <label for="subscribe">подписка на рассылку новостей:</label>
        <input name="" type="text" placeholder="Введите Ваш электронный адрес" class="txt">
        <button type="submit">Подписаться</button>
      </div>
      <div class="communications">
        <div class="tit">наши контакты и региональные отделения: <a href="#"><span>Кыргызстан, Бишкек</span></a></div>
        <div class="sub">720001 Кыргызстан, Бишкек пр-т Манаса 40, офис 321</div>
        <p><span class="i_phone">+996 312 <strong>69 69 31</strong></span></p>
        <p><span class="i_mobile">+996 555 <strong>47 48 49</strong></span></p>
        <p><span class="i_email"><a href="#">info@site.com</a></span></p>
        <p><span class="i_skype"><a href="#">skypename</a></span></p>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="social">
        <div class="tit">мы в социальных сетях:</div>
        <a href="#"><img src="<%= asset_url 'tmp/s_facebook.gif' %>" width="23" height="23" alt="Мы на Facebook"></a>
        <a href="#"><img src="<%= asset_url 'tmp/s_twitter.gif' %>" width="23" height="23" alt="Мы в Twitter"></a>
        <a href="#"><img src="<%= asset_url 'tmp/s_gplus.gif' %>" width="23" height="23" alt="Мы в Google+"></a>
        <a href="#"><img src="<%= asset_url 'tmp/s_vk.gif' %>" width="23" height="23" alt="Мы в VK"></a>
        <a href="#"><img src="<%= asset_url 'tmp/s_odnoklassniki.gif' %>" width="23" height="23" alt="Мы в Одноклассниках"></a>
        <a href="#"><img src="<%= asset_url 'tmp/s_moimir.gif' %>" width="23" height="23" alt="Мы в Моем Мире"></a>
      </div>
      <div class="auction">
        <div class="tit">авто представленны с аукционов:</div>
        <img src="<%= asset_url 'tmp/auction.gif' %>" width="241" height="102" alt="Аукционы">
      </div>
    </div>
  </div>
  <div class="copyright">
      &copy; www.sitename.com, 2013
      <span class="author"><a href="#">spalmalo inc.</a></span>
  </div>
</footer>

app/views/cars/auction.html.erb
	<% content_for :title, "Auction" %>	
			<div id="inner_page">
				
				<div class="subheader">
					<div class="theme">
						<img src="<%=asset_url 'theme/theme_auction.jpg'%>" alt="@" class="img-responsive">
						<h1>Авто с аукциона</h1>
					</div>
				</div>
				<%= render partial:'filter',locals:{path: auction_path} %>

				<div class="results">
					<div class="filter">
						<ul>
							<li><%= link_to 'новые авто', auction_url(params.merge( state: 'new')), class: "#{'active' if params[:state] == 'new'}" %></li>
							<li><%= link_to 'авто б\у', auction_url(params.merge( state: 'used')), class: "#{'active' if params[:state] == 'used'}" %></li>
							<li><%= link_to 'аварийные авто', params.merge( state: 'damaged'), class: "#{'active' if params[:state] == 'damaged'}" %></li>
						</ul>
					</div>
					<div class="listing">
						<%= render @cars %>
					</div>
				</div><!-- //results -->

				<div class="paginator">
				<%= paginate @cars %>
				</div><!-- //paginator -->

			</div>

app/views/cars/catalog.html.erb
<% content_for :title, "Catalog" %>
			<div id="inner_page">
				
				<div class="subheader">
					<div class="theme">
						<img src="<%=asset_url 'theme/theme_catalog.jpg'%>" alt="@" class="img-responsive">
						<h1>Каталог</h1>
					</div>
				</div>
				<%= render partial:'filter',locals:{path: catalog_path} %>

				<div class="results">
					<div class="heading">
						Авто в наличии:
					</div>
					<div class="listing">
						<%= render @cars %>
					</div>
				</div><!-- //results -->

				<div class="paginator">
				<%= paginate @cars %>
				</div><!-- //paginator -->

			</div>

app/views/cars/index.html.erb
<% content_for :title, "Home" %>
<%= render 'hint' %>
<div id="slider">
  <div class="item"></div>
  <a href="#"><img src="<%= asset_url 'tmp/slide1.jpg' %>" alt="@" class="img-responsive"></a>
</div>
<%= render partial:'filter',locals:{path: cars_path} %>

<div class="featured">
  <div class="row">
    <div class="col-lg-4">
      <div class="item itm_delivery">
        <div class="tit">Доставка авто в <br> <a href="#">любой регион РФ</a></div>
        <p>Lorem Ipsum - это текст-"рыба", часто используемый в печати</p>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="item itm_parts">
        <div class="tit">Запчасти <br> на заказ</div>
        <p>Lorem Ipsum является стандартной "рыбой" для текстов на латинице</p>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="item itm_expert">
        <div class="tit">Экспертиза <br> авто</div>
        <p>Его популяризации в новое время послужили публикация листов Letraset</p>
      </div>
    </div>
  </div>
</div><!-- /featured -->

<div class="megafilter clearfix">
  <div class="leftmenu">
    <ul>
      <% %w(sedan suv pickup truck fullsize coupe hatchback  moto).zip(["Автомобили", "SUV", "Пикапы", "Тяжелые грузовики", "Средние грузовоики", "Классика", "Для отдыха", "Мотоциклы"]).each do |body_type, text| %>
        <li><%= link_to text, cars_url(params.merge(:q=>{:car_body_eq=>body_type})), class: "#{'active' if params[:q][:car_body_eq]==body_type}" %></li>
        <% end %>
      <li><a href="#">Гидроциклы</a></li>
      <li><a href="#">Квадроциклы</a></li>
      <li><a href="#">Лодки</a></li>
      <li><a href="#">Прицепы</a></li>
      <li><a href="#">Пром. обор-е</a></li>
    </ul>
  </div>
  <div class="content">
    <div class="topmenu">
      <ul>
        <li><a href="#">Скоро в продаже</a></li>
        <li><a href="#" class="active">В наличии</a></li>
        <li><a href="#">Требуют починки</a></li>
        <li><a href="#">Аварийные</a></li>
        <li><a href="#">На разбор</a></li>
      </ul>
    </div>
    <div class="cards clearfix">
      <%= render @cars %>
    </div>
    <div class="all"><a href="#">смотреть все</a></div>
  </div>
</div><!-- /megafilter -->

<div class="row">
  <div class="col-lg-9">
    <div class="calculator forms">
      <form action="" method="post">
      <div class="head">
        <span class="tit">Таможенный кальуклятор</span>
        <span class="with_delivery">
          <input type="checkbox" id="deliveryID">
          <label for="deliveryID">с доставкой</label>
        </span>
      </div>
      <div class="row">
        <div class="col-lg-6">
          <div class="form-group">
            <label>Страна прибытия:</label>
            <select>
              <option>Россия</option>
              <option value="">Новая Зеландия</option>
            </select>
          </div>
          <div class="form-group form-volume">
            <label for="">Объем:</label>
            <input type="text" value="9999" id="">
            <span class="lbl">см<sup>2</sup></span>
          </div>
          <div class="form-group form-power">
            <label for="">Мощность:</label>
            <input type="text" value="9999" id="">
            <div class="variant">
              <div><label for="horsepowerID"><input type="radio" name="" value="" id="horsepowerID">л.c.</label></div>
              <div><label for="kwID"><input type="radio" name="" value="" id="kwID">кВт</label></div>
            </div>
          </div>
          <div class="clearfix"></div>
          <div class="form-group">
            <legend>Тип двигателя:</legend>
            <div class="group left">
              <label for="gasolineID"><input type="radio" name="" value="" id="gasolineID">бензин</label>
            </div>
            <div class="group left">
              <label for="dieselID"><input type="radio" name="" value="" id="dieselID">дизель</label>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="form-group form-price">
            <label for="priceID">Цена</label>
            <input type="text" id="priceID" value="1">
            <select name="" id="">
              <option value="">бел.р.</option>
            </select>
          </div>
          <div class="form-group">
            <label for="">Год выпуска:</label>
            <select name="" id="">
              <option value="">2010</option>
            </select>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="form-group">
            <legend>Ввозит:</legend>
            <div class="group left">
              <label for=""><input type="radio">физ.лицо</label>
            </div>
            <div class="group left">
              <label for=""><input type="radio">юр.лицо</label>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="form-group">
            <legend>Незнаю как назвать пункт:</legend>
            <div class="group left">
              <label for=""><input type="radio">ZIP</label>
            </div>
            <div class="group left">
              <label for=""><input type="radio">VIN</label>
            </div>
            <div class="group left">
              <label for=""><input type="radio">Отправка (?)</label>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="form-group">
            <label for="">Место отправки</label>
            <select name="" id="">
              <option value="">Орландо</option>
            </select>
          </div>
          <div class="form-group">
            <label for="">Порт прибытия:</label>
            <select name="" id="">
              <option value="">Москва</option>
            </select>
          </div>
          <button type="submit">Пересчитать</button>
        </div>
      </div>
      </form>
    </div>
    <div class="result">
      <div class="row">
        <div class="col-lg-6">
          <div class="item">
            <div class="lebel">Стоимость растоможки авто:</div>
            <div class="price"><strong>14 321</strong> бел. р.</div>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="item">
            <div class="lebel">Стоимость доставки авто:</div>
            <div class="price"><strong>14 321</strong> бел. р.</div>  
          </div>
        </div>
      </div>
      <div class="summery">
        <div class="item">
          <div class="lebel">Общая стоиомть авто по прибытию в Ваш регион:</div>
          <div class="price"><strong>8 877 367</strong> бел. р.</div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="contacts">
      <div class="head">
        <a href="#"><span>Кыргызстан, Бишкек</span></a>
      </div>
      <div class="tit">Контакты</div>
      <p class="sub">720001 Кыргызстан, Бишкек<br> пр-т Манаса 40, офис 321</p>
      <p><span class="i_phone">+996 312 <strong>69 69 31</strong></span></p>
      <p><span class="i_mobile">+996 555 <strong>47 48 49</strong></span></p>
      <p><span class="i_email"><a href="#">info@site.com</a></span></p>
      <p><span class="i_skype"><a href="#">skypename</a></span></p>
      <p class="desc">текст о том что можно поискать представительства и партнеров в своем регоине</p>
    </div>
  </div>
</div>
<%= render 'footer' %>

app/views/cars/search.html.erb
<% content_for :title, "Search" %>		
			<div id="inner_page">
				
				<div class="subheader">
					<div class="theme">
						<img src="<%=asset_url 'theme/theme_search.jpg'%>" alt="@" class="img-responsive">
						<h1>Поиск</h1>
					</div>
				</div>
			<%= render partial:'filter',locals:{path: search_path} %>
				<div class="results">
					<div class="heading">
						Результаты поиска:
					</div>
					<div class="listing">
						<%= render @cars %>
					</div>
				</div><!-- //results -->

				<div class="paginator">
				<%= paginate @cars %>
				</div><!-- //paginator -->
			</div>


app/views/shared/_sidebar.html.erb
<div id="sidebar" class="col-lg-2">
  <div id="logo"><a href="<%=root_path%>"><img src="<%= asset_url 'logo.png' %>" width="140" height="32" alt="SDS Global Shipping"></a></div>
  <% if user_signed_in? %>
    <div class="account">
      <div class="avatar">
        <!-- <a href="#"><img src="<%#= current_user.avatar.url(:medium) %>" alt=""></a> -->
      </div>
      <div class="usermenu">
        <ul>
          <li><a href="<%= profile_path%>" class="u_profile" ></a></li>
          <li><a href="<%= edit_user_registration_path%>" class="u_edit"></a></li>
          <li><a href="<%= destroy_user_session_path%>" data-method="DELETE" class="u_logout"></a></li>
        </ul>
      </div>
      <div class="username"><a href="<%= profile_path%>"><%= "#{current_user.name}  #{current_user.last_name}"%> </a></div>
    </div>
  <% else%>
    <div class="authorization">
      <ul>
        <li><a href="#signup" data-toggle="modal" data-target="#myModal" class="signup">Регистрация</a></li>
        <li><a href="#signin" data-toggle="modal" data-target="#myModal">Войти</a></li>
      </ul>
    </div>
  <% end%>
  <div id="mainmenu">
    <ul>
      <li><%=link_to 'поиск авто', search_url, class: "m_search #{'active' if params[:action]=='search'}"%>" class="m_search"> %></li>
      <li><%=link_to 'каталог авто', catalog_url, class: "m_catalog #{'active' if params[:action]=='catalog'}"%></li>
      <li><%=link_to 'машины с <br> аукциона'.html_safe, auction_url, class: "m_auction #{'active' if params[:action]=='auction'}"%></li>
      <li><a href="#" class="m_emergency">аварийные <br> автомобили</a></li>
      <li><a href="#" class="m_new">новые авто</a></li>
      <li><a href="#" class="m_delivery">доставка</a></li>
      <li><a href="#" class="m_parts">запчасти <br> и аксесуары</a></li>
      <li><a href="#" class="m_expert">экспертиза <br> автомобиля</a></li>
      <li><%=link_to 'о нас', about_url, class: "m_about #{'active' if params[:action]=='about'}"%></li>
      <li><a href="#" class="m_contacts">контакты</a></li>
      <li><%=link_to 'F.A.Q.', faq_url, class: "m_faq #{'active' if params[:action]=='faq'}"%></li>
      <li><a href="#" class="m_cooperation">сотрудничество</a></li> 
    </ul>
  </div>
  <div class="lang">
    язык: <a href="#"><span class="ru">русский</span></a>
  </div>
  <div class="geo">
    <a href="#"><span>Кыргызстан, Бишкек</span></a>
  </div>
</div><!-- #sidebar -->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <ul class="nav nav-tabs" id="myTab">
        <li class="n_signin"><a href="#signin">Вход в систему</a></li>
        <li class="n_signup"><a href="#signup">Регистрация</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="signin">
          <%= form_for resource, :as=>resource_name, :url => session_path(resource_name), :html => {:class =>'forms'} do |f| %>
            <div class="full">
              <div class="item">
                <%= f.label :email %><br />
                <%= f.email_field :email, :autofocus => true %>
              </div>
            </div>
            <div class="item">
              <%= f.label :password %><br />
              <%= f.password_field :password %>
              <div class="forgot"><a href="#">Забыли пароль?</a></div>
            </div>
            <div><%= f.button "Войти" %></div>
          <% end%>
        </div>
        <div class="tab-pane" id="signup">
          <div class="forms">
            <%=form_for(resource, :as => resource_name, :html=>{ :multipart => true}, :url =>  registration_path(resource_name)) do |f| %>
            <%= devise_error_messages! %>
              <div class="half">
                <div class="item mr20">
                  <div><%= f.label :name %><br /></div>
                  <div><%= f.text_field :name, :autofocus => true %><br /></div>
                </div>
                <div class="item">
                  <div><%= f.label :second_name %><br /></div>
                  <div><%= f.text_field :last_name %><br /></div>
                </div>
              </div>
              <div class="full">
                <div class="item">
                  <div><%= f.label :address %><br /></div>
                  <div><%= f.text_field :address %><br /></div>
                </div>
              </div class="full">
              <div class="full">
                <div class="item">
                  <div><%= f.label :avatar %><br /></div>
                  <div><%= f.file_field :avatar %><br /></div>
                </div>
              </div>
              <div class="full">
                <div class="item">
                  <div><%= f.label :email %><br />
                  <%= f.email_field :email%></div>
                </div>
              </div>
              <div class="half">
                <div class="item mr20">
                  <div><%= f.label :password %><br />
                    <%= f.password_field :password %></div>
                </div>
                <div class="item">
                <div><%= f.label :password_confirmation %><br />
                  <%= f.password_field :password_confirmation %></div>
                </div>
              </div>
              <div><%= f.button  "Зарегистрироваться" %></div>
            <% end%>
          </div><!-- //forms -->
        </div>
      </div>
    </div>
  </div>
</div>